
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateEventEmitterH.js
 */
#pragma once

#include <react/renderer/components/view/ViewEventEmitter.h>


namespace facebook::react {
class RNCVideoEventEmitter : public ViewEventEmitter {
 public:
  using ViewEventEmitter::ViewEventEmitter;

  struct OnControlsVisibilityChange {
      bool isVisible;
    };

  struct OnVideoLoadNaturalSize {
      Float width;
    Float height;
    std::string orientation;
    };

  struct OnVideoLoadAudioTracks {
      int index;
    std::string title;
    std::string language;
    Float bitrate;
    std::string type;
    bool selected;
    };

  struct OnVideoLoadTextTracks {
      int index;
    std::string title;
    std::string language;
    std::string type;
    bool selected;
    };

  struct OnVideoLoad {
      Float currentTime;
    Float duration;
    OnVideoLoadNaturalSize naturalSize;
    std::vector<OnVideoLoadAudioTracks> audioTracks;
    std::vector<OnVideoLoadTextTracks> textTracks;
    };

  struct OnVideoLoadStart {
      bool isNetwork;
    std::string type;
    std::string uri;
    };

  struct OnVideoAspectRatio {
      Float width;
    Float height;
    };

  struct OnVideoBuffer {
      bool isBuffering;
    };

  struct OnVideoErrorError {
      std::string errorString;
    std::string errorException;
    std::string errorStackTrace;
    std::string errorCode;
    std::string error;
    int code;
    std::string localizedDescription;
    std::string localizedFailureReason;
    std::string localizedRecoverySuggestion;
    std::string domain;
    };

  struct OnVideoError {
      OnVideoErrorError error;
    int target;
    };

  struct OnVideoProgress {
      Float currentTime;
    Float playableDuration;
    Float seekableDuration;
    };

  struct OnVideoBandwidthUpdate {
      int bitrate;
    Float width;
    Float height;
    int trackId;
    };

  struct OnVideoSeek {
      Float currentTime;
    Float seekTime;
    };

  struct OnVideoEnd {
      
    };

  struct OnVideoAudioBecomingNoisy {
      
    };

  struct OnVideoFullscreenPlayerWillPresent {
      
    };

  struct OnVideoFullscreenPlayerDidPresent {
      
    };

  struct OnVideoFullscreenPlayerWillDismiss {
      
    };

  struct OnVideoFullscreenPlayerDidDismiss {
      
    };

  struct OnReadyForDisplay {
      
    };

  struct OnPlaybackRateChange {
      Float playbackRate;
    };

  struct OnVolumeChange {
      Float volume;
    };

  struct OnVideoExternalPlaybackChange {
      bool isExternalPlaybackActive;
    };

  struct OnGetLicense {
      std::string licenseUrl;
    std::string loadedLicenseUrl;
    std::string contentId;
    std::string spcBase64;
    };

  struct OnPictureInPictureStatusChanged {
      bool isActive;
    };

  struct OnRestoreUserInterfaceForPictureInPictureStop {
      
    };

  struct OnReceiveAdEventData {
      
    };

  struct OnReceiveAdEvent {
      OnReceiveAdEventData data;
    std::string event;
    };

  struct OnVideoPlaybackStateChanged {
      bool isPlaying;
    bool isSeeking;
    };

  struct OnVideoIdle {
      
    };

  struct OnAudioFocusChanged {
      bool hasAudioFocus;
    };

  struct OnTimedMetadataMetadata {
      std::string value;
    std::string identifier;
    };

  struct OnTimedMetadata {
      std::vector<OnTimedMetadataMetadata> metadata;
    };

  struct OnAudioTracksAudioTracks {
      int index;
    std::string title;
    std::string language;
    Float bitrate;
    std::string type;
    bool selected;
    };

  struct OnAudioTracks {
      std::vector<OnAudioTracksAudioTracks> audioTracks;
    };

  struct OnTextTracksTextTracks {
      int index;
    std::string title;
    std::string language;
    std::string type;
    bool selected;
    };

  struct OnTextTracks {
      std::vector<OnTextTracksTextTracks> textTracks;
    };

  struct OnTextTrackDataChanged {
      std::string subtitleTracks;
    };

  struct OnVideoTracksVideoTracks {
      int index;
    std::string tracksId;
    std::string codecs;
    Float width;
    Float height;
    Float bitrate;
    bool selected;
    };

  struct OnVideoTracks {
      std::vector<OnVideoTracksVideoTracks> videoTracks;
    };
  void onControlsVisibilityChange(OnControlsVisibilityChange value) const;

  void onVideoLoad(OnVideoLoad value) const;

  void onVideoLoadStart(OnVideoLoadStart value) const;

  void onVideoAspectRatio(OnVideoAspectRatio value) const;

  void onVideoBuffer(OnVideoBuffer value) const;

  void onVideoError(OnVideoError value) const;

  void onVideoProgress(OnVideoProgress value) const;

  void onVideoBandwidthUpdate(OnVideoBandwidthUpdate value) const;

  void onVideoSeek(OnVideoSeek value) const;

  void onVideoEnd(OnVideoEnd value) const;

  void onVideoAudioBecomingNoisy(OnVideoAudioBecomingNoisy value) const;

  void onVideoFullscreenPlayerWillPresent(OnVideoFullscreenPlayerWillPresent value) const;

  void onVideoFullscreenPlayerDidPresent(OnVideoFullscreenPlayerDidPresent value) const;

  void onVideoFullscreenPlayerWillDismiss(OnVideoFullscreenPlayerWillDismiss value) const;

  void onVideoFullscreenPlayerDidDismiss(OnVideoFullscreenPlayerDidDismiss value) const;

  void onReadyForDisplay(OnReadyForDisplay value) const;

  void onPlaybackRateChange(OnPlaybackRateChange value) const;

  void onVolumeChange(OnVolumeChange value) const;

  void onVideoExternalPlaybackChange(OnVideoExternalPlaybackChange value) const;

  void onGetLicense(OnGetLicense value) const;

  void onPictureInPictureStatusChanged(OnPictureInPictureStatusChanged value) const;

  void onRestoreUserInterfaceForPictureInPictureStop(OnRestoreUserInterfaceForPictureInPictureStop value) const;

  void onReceiveAdEvent(OnReceiveAdEvent value) const;

  void onVideoPlaybackStateChanged(OnVideoPlaybackStateChanged value) const;

  void onVideoIdle(OnVideoIdle value) const;

  void onAudioFocusChanged(OnAudioFocusChanged value) const;

  void onTimedMetadata(OnTimedMetadata value) const;

  void onAudioTracks(OnAudioTracks value) const;

  void onTextTracks(OnTextTracks value) const;

  void onTextTrackDataChanged(OnTextTrackDataChanged value) const;

  void onVideoTracks(OnVideoTracks value) const;
};
} // namespace facebook::react
