
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateEventEmitterCpp.js
 */

#include "EventEmitters.h"


namespace facebook::react {

void RNCVideoEventEmitter::onControlsVisibilityChange(OnControlsVisibilityChange $event) const {
  dispatchEvent("controlsVisibilityChange", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    $payload.setProperty(runtime, "isVisible", $event.isVisible);
    return $payload;
  });
}


void RNCVideoEventEmitter::onVideoLoad(OnVideoLoad $event) const {
  dispatchEvent("videoLoad", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    $payload.setProperty(runtime, "currentTime", $event.currentTime);
$payload.setProperty(runtime, "duration", $event.duration);
{
  auto naturalSize = jsi::Object(runtime);
  naturalSize.setProperty(runtime, "width", $event.naturalSize.width);
  naturalSize.setProperty(runtime, "height", $event.naturalSize.height);
  naturalSize.setProperty(runtime, "orientation", $event.naturalSize.orientation);
  $payload.setProperty(runtime, "naturalSize", naturalSize);
}

    auto audioTracks = jsi::Array(runtime, $event.audioTracks.size());
    size_t audioTracksIndex = 0;
    for (auto audioTracksValue : $event.audioTracks) {
      auto audioTracksObject = jsi::Object(runtime);
      audioTracksObject.setProperty(runtime, "index", audioTracksValue.index);
audioTracksObject.setProperty(runtime, "title", audioTracksValue.title);
audioTracksObject.setProperty(runtime, "language", audioTracksValue.language);
audioTracksObject.setProperty(runtime, "bitrate", audioTracksValue.bitrate);
audioTracksObject.setProperty(runtime, "type", audioTracksValue.type);
audioTracksObject.setProperty(runtime, "selected", audioTracksValue.selected);
      audioTracks.setValueAtIndex(runtime, audioTracksIndex++, audioTracksObject);
    }
    $payload.setProperty(runtime, "audioTracks", audioTracks);
  

    auto textTracks = jsi::Array(runtime, $event.textTracks.size());
    size_t textTracksIndex = 0;
    for (auto textTracksValue : $event.textTracks) {
      auto textTracksObject = jsi::Object(runtime);
      textTracksObject.setProperty(runtime, "index", textTracksValue.index);
textTracksObject.setProperty(runtime, "title", textTracksValue.title);
textTracksObject.setProperty(runtime, "language", textTracksValue.language);
textTracksObject.setProperty(runtime, "type", textTracksValue.type);
textTracksObject.setProperty(runtime, "selected", textTracksValue.selected);
      textTracks.setValueAtIndex(runtime, textTracksIndex++, textTracksObject);
    }
    $payload.setProperty(runtime, "textTracks", textTracks);
  
    return $payload;
  });
}


void RNCVideoEventEmitter::onVideoLoadStart(OnVideoLoadStart $event) const {
  dispatchEvent("videoLoadStart", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    $payload.setProperty(runtime, "isNetwork", $event.isNetwork);
$payload.setProperty(runtime, "type", $event.type);
$payload.setProperty(runtime, "uri", $event.uri);
    return $payload;
  });
}


void RNCVideoEventEmitter::onVideoAspectRatio(OnVideoAspectRatio $event) const {
  dispatchEvent("videoAspectRatio", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    $payload.setProperty(runtime, "width", $event.width);
$payload.setProperty(runtime, "height", $event.height);
    return $payload;
  });
}


void RNCVideoEventEmitter::onVideoBuffer(OnVideoBuffer $event) const {
  dispatchEvent("videoBuffer", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    $payload.setProperty(runtime, "isBuffering", $event.isBuffering);
    return $payload;
  });
}


void RNCVideoEventEmitter::onVideoError(OnVideoError $event) const {
  dispatchEvent("videoError", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    {
  auto error = jsi::Object(runtime);
  error.setProperty(runtime, "errorString", $event.error.errorString);
  error.setProperty(runtime, "errorException", $event.error.errorException);
  error.setProperty(runtime, "errorStackTrace", $event.error.errorStackTrace);
  error.setProperty(runtime, "errorCode", $event.error.errorCode);
  error.setProperty(runtime, "error", $event.error.error);
  error.setProperty(runtime, "code", $event.error.code);
  error.setProperty(runtime, "localizedDescription", $event.error.localizedDescription);
  error.setProperty(runtime, "localizedFailureReason", $event.error.localizedFailureReason);
  error.setProperty(runtime, "localizedRecoverySuggestion", $event.error.localizedRecoverySuggestion);
  error.setProperty(runtime, "domain", $event.error.domain);
  $payload.setProperty(runtime, "error", error);
}
$payload.setProperty(runtime, "target", $event.target);
    return $payload;
  });
}


void RNCVideoEventEmitter::onVideoProgress(OnVideoProgress $event) const {
  dispatchEvent("videoProgress", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    $payload.setProperty(runtime, "currentTime", $event.currentTime);
$payload.setProperty(runtime, "playableDuration", $event.playableDuration);
$payload.setProperty(runtime, "seekableDuration", $event.seekableDuration);
    return $payload;
  });
}


void RNCVideoEventEmitter::onVideoBandwidthUpdate(OnVideoBandwidthUpdate $event) const {
  dispatchEvent("videoBandwidthUpdate", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    $payload.setProperty(runtime, "bitrate", $event.bitrate);
$payload.setProperty(runtime, "width", $event.width);
$payload.setProperty(runtime, "height", $event.height);
$payload.setProperty(runtime, "trackId", $event.trackId);
    return $payload;
  });
}


void RNCVideoEventEmitter::onVideoSeek(OnVideoSeek $event) const {
  dispatchEvent("videoSeek", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    $payload.setProperty(runtime, "currentTime", $event.currentTime);
$payload.setProperty(runtime, "seekTime", $event.seekTime);
    return $payload;
  });
}


void RNCVideoEventEmitter::onVideoEnd(OnVideoEnd $event) const {
  dispatchEvent("videoEnd", [](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    
    return $payload;
  });
}


void RNCVideoEventEmitter::onVideoAudioBecomingNoisy(OnVideoAudioBecomingNoisy $event) const {
  dispatchEvent("videoAudioBecomingNoisy", [](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    
    return $payload;
  });
}


void RNCVideoEventEmitter::onVideoFullscreenPlayerWillPresent(OnVideoFullscreenPlayerWillPresent $event) const {
  dispatchEvent("videoFullscreenPlayerWillPresent", [](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    
    return $payload;
  });
}


void RNCVideoEventEmitter::onVideoFullscreenPlayerDidPresent(OnVideoFullscreenPlayerDidPresent $event) const {
  dispatchEvent("videoFullscreenPlayerDidPresent", [](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    
    return $payload;
  });
}


void RNCVideoEventEmitter::onVideoFullscreenPlayerWillDismiss(OnVideoFullscreenPlayerWillDismiss $event) const {
  dispatchEvent("videoFullscreenPlayerWillDismiss", [](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    
    return $payload;
  });
}


void RNCVideoEventEmitter::onVideoFullscreenPlayerDidDismiss(OnVideoFullscreenPlayerDidDismiss $event) const {
  dispatchEvent("videoFullscreenPlayerDidDismiss", [](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    
    return $payload;
  });
}


void RNCVideoEventEmitter::onReadyForDisplay(OnReadyForDisplay $event) const {
  dispatchEvent("readyForDisplay", [](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    
    return $payload;
  });
}


void RNCVideoEventEmitter::onPlaybackRateChange(OnPlaybackRateChange $event) const {
  dispatchEvent("playbackRateChange", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    $payload.setProperty(runtime, "playbackRate", $event.playbackRate);
    return $payload;
  });
}


void RNCVideoEventEmitter::onVolumeChange(OnVolumeChange $event) const {
  dispatchEvent("volumeChange", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    $payload.setProperty(runtime, "volume", $event.volume);
    return $payload;
  });
}


void RNCVideoEventEmitter::onVideoExternalPlaybackChange(OnVideoExternalPlaybackChange $event) const {
  dispatchEvent("videoExternalPlaybackChange", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    $payload.setProperty(runtime, "isExternalPlaybackActive", $event.isExternalPlaybackActive);
    return $payload;
  });
}


void RNCVideoEventEmitter::onGetLicense(OnGetLicense $event) const {
  dispatchEvent("getLicense", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    $payload.setProperty(runtime, "licenseUrl", $event.licenseUrl);
$payload.setProperty(runtime, "loadedLicenseUrl", $event.loadedLicenseUrl);
$payload.setProperty(runtime, "contentId", $event.contentId);
$payload.setProperty(runtime, "spcBase64", $event.spcBase64);
    return $payload;
  });
}


void RNCVideoEventEmitter::onPictureInPictureStatusChanged(OnPictureInPictureStatusChanged $event) const {
  dispatchEvent("pictureInPictureStatusChanged", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    $payload.setProperty(runtime, "isActive", $event.isActive);
    return $payload;
  });
}


void RNCVideoEventEmitter::onRestoreUserInterfaceForPictureInPictureStop(OnRestoreUserInterfaceForPictureInPictureStop $event) const {
  dispatchEvent("restoreUserInterfaceForPictureInPictureStop", [](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    
    return $payload;
  });
}


void RNCVideoEventEmitter::onReceiveAdEvent(OnReceiveAdEvent $event) const {
  dispatchEvent("receiveAdEvent", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    {
  auto data = jsi::Object(runtime);
  
  $payload.setProperty(runtime, "data", data);
}
$payload.setProperty(runtime, "event", $event.event);
    return $payload;
  });
}


void RNCVideoEventEmitter::onVideoPlaybackStateChanged(OnVideoPlaybackStateChanged $event) const {
  dispatchEvent("videoPlaybackStateChanged", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    $payload.setProperty(runtime, "isPlaying", $event.isPlaying);
$payload.setProperty(runtime, "isSeeking", $event.isSeeking);
    return $payload;
  });
}


void RNCVideoEventEmitter::onVideoIdle(OnVideoIdle $event) const {
  dispatchEvent("videoIdle", [](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    
    return $payload;
  });
}


void RNCVideoEventEmitter::onAudioFocusChanged(OnAudioFocusChanged $event) const {
  dispatchEvent("audioFocusChanged", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    $payload.setProperty(runtime, "hasAudioFocus", $event.hasAudioFocus);
    return $payload;
  });
}


void RNCVideoEventEmitter::onTimedMetadata(OnTimedMetadata $event) const {
  dispatchEvent("timedMetadata", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    
    auto metadata = jsi::Array(runtime, $event.metadata.size());
    size_t metadataIndex = 0;
    for (auto metadataValue : $event.metadata) {
      auto metadataObject = jsi::Object(runtime);
      metadataObject.setProperty(runtime, "value", metadataValue.value);
metadataObject.setProperty(runtime, "identifier", metadataValue.identifier);
      metadata.setValueAtIndex(runtime, metadataIndex++, metadataObject);
    }
    $payload.setProperty(runtime, "metadata", metadata);
  
    return $payload;
  });
}


void RNCVideoEventEmitter::onAudioTracks(OnAudioTracks $event) const {
  dispatchEvent("audioTracks", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    
    auto audioTracks = jsi::Array(runtime, $event.audioTracks.size());
    size_t audioTracksIndex = 0;
    for (auto audioTracksValue : $event.audioTracks) {
      auto audioTracksObject = jsi::Object(runtime);
      audioTracksObject.setProperty(runtime, "index", audioTracksValue.index);
audioTracksObject.setProperty(runtime, "title", audioTracksValue.title);
audioTracksObject.setProperty(runtime, "language", audioTracksValue.language);
audioTracksObject.setProperty(runtime, "bitrate", audioTracksValue.bitrate);
audioTracksObject.setProperty(runtime, "type", audioTracksValue.type);
audioTracksObject.setProperty(runtime, "selected", audioTracksValue.selected);
      audioTracks.setValueAtIndex(runtime, audioTracksIndex++, audioTracksObject);
    }
    $payload.setProperty(runtime, "audioTracks", audioTracks);
  
    return $payload;
  });
}


void RNCVideoEventEmitter::onTextTracks(OnTextTracks $event) const {
  dispatchEvent("textTracks", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    
    auto textTracks = jsi::Array(runtime, $event.textTracks.size());
    size_t textTracksIndex = 0;
    for (auto textTracksValue : $event.textTracks) {
      auto textTracksObject = jsi::Object(runtime);
      textTracksObject.setProperty(runtime, "index", textTracksValue.index);
textTracksObject.setProperty(runtime, "title", textTracksValue.title);
textTracksObject.setProperty(runtime, "language", textTracksValue.language);
textTracksObject.setProperty(runtime, "type", textTracksValue.type);
textTracksObject.setProperty(runtime, "selected", textTracksValue.selected);
      textTracks.setValueAtIndex(runtime, textTracksIndex++, textTracksObject);
    }
    $payload.setProperty(runtime, "textTracks", textTracks);
  
    return $payload;
  });
}


void RNCVideoEventEmitter::onTextTrackDataChanged(OnTextTrackDataChanged $event) const {
  dispatchEvent("textTrackDataChanged", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    $payload.setProperty(runtime, "subtitleTracks", $event.subtitleTracks);
    return $payload;
  });
}


void RNCVideoEventEmitter::onVideoTracks(OnVideoTracks $event) const {
  dispatchEvent("videoTracks", [$event=std::move($event)](jsi::Runtime &runtime) {
    auto $payload = jsi::Object(runtime);
    
    auto videoTracks = jsi::Array(runtime, $event.videoTracks.size());
    size_t videoTracksIndex = 0;
    for (auto videoTracksValue : $event.videoTracks) {
      auto videoTracksObject = jsi::Object(runtime);
      videoTracksObject.setProperty(runtime, "index", videoTracksValue.index);
videoTracksObject.setProperty(runtime, "tracksId", videoTracksValue.tracksId);
videoTracksObject.setProperty(runtime, "codecs", videoTracksValue.codecs);
videoTracksObject.setProperty(runtime, "width", videoTracksValue.width);
videoTracksObject.setProperty(runtime, "height", videoTracksValue.height);
videoTracksObject.setProperty(runtime, "bitrate", videoTracksValue.bitrate);
videoTracksObject.setProperty(runtime, "selected", videoTracksValue.selected);
      videoTracks.setValueAtIndex(runtime, videoTracksIndex++, videoTracksObject);
    }
    $payload.setProperty(runtime, "videoTracks", videoTracks);
  
    return $payload;
  });
}

} // namespace facebook::react
