
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include "Props.h"
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook::react {

RNCVideoProps::RNCVideoProps(
    const PropsParserContext &context,
    const RNCVideoProps &sourceProps,
    const RawProps &rawProps): ViewProps(context, sourceProps, rawProps),

    src(convertRawProp(context, rawProps, "src", sourceProps.src, {})),
    allowsExternalPlayback(convertRawProp(context, rawProps, "allowsExternalPlayback", sourceProps.allowsExternalPlayback, {false})),
    disableFocus(convertRawProp(context, rawProps, "disableFocus", sourceProps.disableFocus, {false})),
    maxBitRate(convertRawProp(context, rawProps, "maxBitRate", sourceProps.maxBitRate, {0.0})),
    resizeMode(convertRawProp(context, rawProps, "resizeMode", sourceProps.resizeMode, {"none"})),
    repeat(convertRawProp(context, rawProps, "repeat", sourceProps.repeat, {false})),
    automaticallyWaitsToMinimizeStalling(convertRawProp(context, rawProps, "automaticallyWaitsToMinimizeStalling", sourceProps.automaticallyWaitsToMinimizeStalling, {false})),
    shutterColor(convertRawProp(context, rawProps, "shutterColor", sourceProps.shutterColor, {0})),
    audioOutput(convertRawProp(context, rawProps, "audioOutput", sourceProps.audioOutput, {"speaker"})),
    selectedTextTrack(convertRawProp(context, rawProps, "selectedTextTrack", sourceProps.selectedTextTrack, {})),
    selectedAudioTrack(convertRawProp(context, rawProps, "selectedAudioTrack", sourceProps.selectedAudioTrack, {})),
    selectedVideoTrack(convertRawProp(context, rawProps, "selectedVideoTrack", sourceProps.selectedVideoTrack, {})),
    paused(convertRawProp(context, rawProps, "paused", sourceProps.paused, {false})),
    muted(convertRawProp(context, rawProps, "muted", sourceProps.muted, {false})),
    controls(convertRawProp(context, rawProps, "controls", sourceProps.controls, {false})),
    filter(convertRawProp(context, rawProps, "filter", sourceProps.filter, {""})),
    filterEnabled(convertRawProp(context, rawProps, "filterEnabled", sourceProps.filterEnabled, {false})),
    volume(convertRawProp(context, rawProps, "volume", sourceProps.volume, {0.0})),
    playInBackground(convertRawProp(context, rawProps, "playInBackground", sourceProps.playInBackground, {false})),
    preventsDisplaySleepDuringVideoPlayback(convertRawProp(context, rawProps, "preventsDisplaySleepDuringVideoPlayback", sourceProps.preventsDisplaySleepDuringVideoPlayback, {false})),
    preferredForwardBufferDuration(convertRawProp(context, rawProps, "preferredForwardBufferDuration", sourceProps.preferredForwardBufferDuration, {0.0})),
    playWhenInactive(convertRawProp(context, rawProps, "playWhenInactive", sourceProps.playWhenInactive, {false})),
    enterPictureInPictureOnLeave(convertRawProp(context, rawProps, "enterPictureInPictureOnLeave", sourceProps.enterPictureInPictureOnLeave, {false})),
    ignoreSilentSwitch(convertRawProp(context, rawProps, "ignoreSilentSwitch", sourceProps.ignoreSilentSwitch, {"inherit"})),
    mixWithOthers(convertRawProp(context, rawProps, "mixWithOthers", sourceProps.mixWithOthers, {"inherit"})),
    rate(convertRawProp(context, rawProps, "rate", sourceProps.rate, {0.0})),
    fullscreen(convertRawProp(context, rawProps, "fullscreen", sourceProps.fullscreen, {false})),
    fullscreenAutorotate(convertRawProp(context, rawProps, "fullscreenAutorotate", sourceProps.fullscreenAutorotate, {false})),
    fullscreenOrientation(convertRawProp(context, rawProps, "fullscreenOrientation", sourceProps.fullscreenOrientation, {"all"})),
    progressUpdateInterval(convertRawProp(context, rawProps, "progressUpdateInterval", sourceProps.progressUpdateInterval, {0.0})),
    restoreUserInterfaceForPIPStopCompletionHandler(convertRawProp(context, rawProps, "restoreUserInterfaceForPIPStopCompletionHandler", sourceProps.restoreUserInterfaceForPIPStopCompletionHandler, {false})),
    debug(convertRawProp(context, rawProps, "debug", sourceProps.debug, {})),
    showNotificationControls(convertRawProp(context, rawProps, "showNotificationControls", sourceProps.showNotificationControls, {false})),
    currentPlaybackTime(convertRawProp(context, rawProps, "currentPlaybackTime", sourceProps.currentPlaybackTime, {0.0})),
    disableDisconnectError(convertRawProp(context, rawProps, "disableDisconnectError", sourceProps.disableDisconnectError, {false})),
    focusable(convertRawProp(context, rawProps, "focusable", sourceProps.focusable, {false})),
    hideShutterView(convertRawProp(context, rawProps, "hideShutterView", sourceProps.hideShutterView, {false})),
    reportBandwidth(convertRawProp(context, rawProps, "reportBandwidth", sourceProps.reportBandwidth, {false})),
    subtitleStyle(convertRawProp(context, rawProps, "subtitleStyle", sourceProps.subtitleStyle, {})),
    viewType(convertRawProp(context, rawProps, "viewType", sourceProps.viewType, {0})),
    bufferingStrategy(convertRawProp(context, rawProps, "bufferingStrategy", sourceProps.bufferingStrategy, {"Default"})),
    controlsStyles(convertRawProp(context, rawProps, "controlsStyles", sourceProps.controlsStyles, {})),
    disableAudioSessionManagement(convertRawProp(context, rawProps, "disableAudioSessionManagement", sourceProps.disableAudioSessionManagement, {false}))
      {}

} // namespace facebook::react
