
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsH.js
 */
#pragma once

#include <react/renderer/components/view/ViewProps.h>
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>
#include <vector>

namespace facebook::react {

struct RNCVideoSrcRequestHeadersStruct {
  std::string key{};
  std::string value{};
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, RNCVideoSrcRequestHeadersStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_key = map.find("key");
  if (tmp_key != map.end()) {
    fromRawValue(context, tmp_key->second, result.key);
  }
  auto tmp_value = map.find("value");
  if (tmp_value != map.end()) {
    fromRawValue(context, tmp_value->second, result.value);
  }
}

static inline std::string toString(const RNCVideoSrcRequestHeadersStruct &value) {
  return "[Object RNCVideoSrcRequestHeadersStruct]";
}

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, std::vector<RNCVideoSrcRequestHeadersStruct> &result) {
  auto items = (std::vector<RawValue>)value;
  for (const auto &item : items) {
    RNCVideoSrcRequestHeadersStruct newItem;
    fromRawValue(context, item, newItem);
    result.emplace_back(newItem);
  }
}


struct RNCVideoSrcMetadataStruct {
  std::string title{};
  std::string subtitle{};
  std::string description{};
  std::string imageUri{};
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, RNCVideoSrcMetadataStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_title = map.find("title");
  if (tmp_title != map.end()) {
    fromRawValue(context, tmp_title->second, result.title);
  }
  auto tmp_subtitle = map.find("subtitle");
  if (tmp_subtitle != map.end()) {
    fromRawValue(context, tmp_subtitle->second, result.subtitle);
  }
  auto tmp_description = map.find("description");
  if (tmp_description != map.end()) {
    fromRawValue(context, tmp_description->second, result.description);
  }
  auto tmp_imageUri = map.find("imageUri");
  if (tmp_imageUri != map.end()) {
    fromRawValue(context, tmp_imageUri->second, result.imageUri);
  }
}

static inline std::string toString(const RNCVideoSrcMetadataStruct &value) {
  return "[Object RNCVideoSrcMetadataStruct]";
}

struct RNCVideoSrcDrmHeadersStruct {
  std::string key{};
  std::string value{};
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, RNCVideoSrcDrmHeadersStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_key = map.find("key");
  if (tmp_key != map.end()) {
    fromRawValue(context, tmp_key->second, result.key);
  }
  auto tmp_value = map.find("value");
  if (tmp_value != map.end()) {
    fromRawValue(context, tmp_value->second, result.value);
  }
}

static inline std::string toString(const RNCVideoSrcDrmHeadersStruct &value) {
  return "[Object RNCVideoSrcDrmHeadersStruct]";
}

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, std::vector<RNCVideoSrcDrmHeadersStruct> &result) {
  auto items = (std::vector<RawValue>)value;
  for (const auto &item : items) {
    RNCVideoSrcDrmHeadersStruct newItem;
    fromRawValue(context, item, newItem);
    result.emplace_back(newItem);
  }
}


struct RNCVideoSrcDrmStruct {
  std::string type{"widevine"};
  std::string licenseServer{};
  std::vector<RNCVideoSrcDrmHeadersStruct> headers{};
  std::string contentId{};
  std::string certificateUrl{};
  bool base64Certificate{false};
  bool useExternalGetLicense{false};
  bool multiDrm{false};
  std::string localSourceEncryptionKeyScheme{};
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, RNCVideoSrcDrmStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_type = map.find("type");
  if (tmp_type != map.end()) {
    fromRawValue(context, tmp_type->second, result.type);
  }
  auto tmp_licenseServer = map.find("licenseServer");
  if (tmp_licenseServer != map.end()) {
    fromRawValue(context, tmp_licenseServer->second, result.licenseServer);
  }
  auto tmp_headers = map.find("headers");
  if (tmp_headers != map.end()) {
    fromRawValue(context, tmp_headers->second, result.headers);
  }
  auto tmp_contentId = map.find("contentId");
  if (tmp_contentId != map.end()) {
    fromRawValue(context, tmp_contentId->second, result.contentId);
  }
  auto tmp_certificateUrl = map.find("certificateUrl");
  if (tmp_certificateUrl != map.end()) {
    fromRawValue(context, tmp_certificateUrl->second, result.certificateUrl);
  }
  auto tmp_base64Certificate = map.find("base64Certificate");
  if (tmp_base64Certificate != map.end()) {
    fromRawValue(context, tmp_base64Certificate->second, result.base64Certificate);
  }
  auto tmp_useExternalGetLicense = map.find("useExternalGetLicense");
  if (tmp_useExternalGetLicense != map.end()) {
    fromRawValue(context, tmp_useExternalGetLicense->second, result.useExternalGetLicense);
  }
  auto tmp_multiDrm = map.find("multiDrm");
  if (tmp_multiDrm != map.end()) {
    fromRawValue(context, tmp_multiDrm->second, result.multiDrm);
  }
  auto tmp_localSourceEncryptionKeyScheme = map.find("localSourceEncryptionKeyScheme");
  if (tmp_localSourceEncryptionKeyScheme != map.end()) {
    fromRawValue(context, tmp_localSourceEncryptionKeyScheme->second, result.localSourceEncryptionKeyScheme);
  }
}

static inline std::string toString(const RNCVideoSrcDrmStruct &value) {
  return "[Object RNCVideoSrcDrmStruct]";
}

struct RNCVideoSrcCmcdRequestStruct {
  std::string key{};
  std::string value{};
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, RNCVideoSrcCmcdRequestStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_key = map.find("key");
  if (tmp_key != map.end()) {
    fromRawValue(context, tmp_key->second, result.key);
  }
  auto tmp_value = map.find("value");
  if (tmp_value != map.end()) {
    fromRawValue(context, tmp_value->second, result.value);
  }
}

static inline std::string toString(const RNCVideoSrcCmcdRequestStruct &value) {
  return "[Object RNCVideoSrcCmcdRequestStruct]";
}

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, std::vector<RNCVideoSrcCmcdRequestStruct> &result) {
  auto items = (std::vector<RawValue>)value;
  for (const auto &item : items) {
    RNCVideoSrcCmcdRequestStruct newItem;
    fromRawValue(context, item, newItem);
    result.emplace_back(newItem);
  }
}


struct RNCVideoSrcCmcdSessionStruct {
  std::string key{};
  std::string value{};
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, RNCVideoSrcCmcdSessionStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_key = map.find("key");
  if (tmp_key != map.end()) {
    fromRawValue(context, tmp_key->second, result.key);
  }
  auto tmp_value = map.find("value");
  if (tmp_value != map.end()) {
    fromRawValue(context, tmp_value->second, result.value);
  }
}

static inline std::string toString(const RNCVideoSrcCmcdSessionStruct &value) {
  return "[Object RNCVideoSrcCmcdSessionStruct]";
}

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, std::vector<RNCVideoSrcCmcdSessionStruct> &result) {
  auto items = (std::vector<RawValue>)value;
  for (const auto &item : items) {
    RNCVideoSrcCmcdSessionStruct newItem;
    fromRawValue(context, item, newItem);
    result.emplace_back(newItem);
  }
}


struct RNCVideoSrcCmcdObjectStruct {
  std::string key{};
  std::string value{};
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, RNCVideoSrcCmcdObjectStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_key = map.find("key");
  if (tmp_key != map.end()) {
    fromRawValue(context, tmp_key->second, result.key);
  }
  auto tmp_value = map.find("value");
  if (tmp_value != map.end()) {
    fromRawValue(context, tmp_value->second, result.value);
  }
}

static inline std::string toString(const RNCVideoSrcCmcdObjectStruct &value) {
  return "[Object RNCVideoSrcCmcdObjectStruct]";
}

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, std::vector<RNCVideoSrcCmcdObjectStruct> &result) {
  auto items = (std::vector<RawValue>)value;
  for (const auto &item : items) {
    RNCVideoSrcCmcdObjectStruct newItem;
    fromRawValue(context, item, newItem);
    result.emplace_back(newItem);
  }
}


struct RNCVideoSrcCmcdStatusStruct {
  std::string key{};
  std::string value{};
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, RNCVideoSrcCmcdStatusStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_key = map.find("key");
  if (tmp_key != map.end()) {
    fromRawValue(context, tmp_key->second, result.key);
  }
  auto tmp_value = map.find("value");
  if (tmp_value != map.end()) {
    fromRawValue(context, tmp_value->second, result.value);
  }
}

static inline std::string toString(const RNCVideoSrcCmcdStatusStruct &value) {
  return "[Object RNCVideoSrcCmcdStatusStruct]";
}

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, std::vector<RNCVideoSrcCmcdStatusStruct> &result) {
  auto items = (std::vector<RawValue>)value;
  for (const auto &item : items) {
    RNCVideoSrcCmcdStatusStruct newItem;
    fromRawValue(context, item, newItem);
    result.emplace_back(newItem);
  }
}


struct RNCVideoSrcCmcdStruct {
  int mode{1};
  std::vector<RNCVideoSrcCmcdRequestStruct> request{};
  std::vector<RNCVideoSrcCmcdSessionStruct> session{};
  std::vector<RNCVideoSrcCmcdObjectStruct> object{};
  std::vector<RNCVideoSrcCmcdStatusStruct> status{};
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, RNCVideoSrcCmcdStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_mode = map.find("mode");
  if (tmp_mode != map.end()) {
    fromRawValue(context, tmp_mode->second, result.mode);
  }
  auto tmp_request = map.find("request");
  if (tmp_request != map.end()) {
    fromRawValue(context, tmp_request->second, result.request);
  }
  auto tmp_session = map.find("session");
  if (tmp_session != map.end()) {
    fromRawValue(context, tmp_session->second, result.session);
  }
  auto tmp_object = map.find("object");
  if (tmp_object != map.end()) {
    fromRawValue(context, tmp_object->second, result.object);
  }
  auto tmp_status = map.find("status");
  if (tmp_status != map.end()) {
    fromRawValue(context, tmp_status->second, result.status);
  }
}

static inline std::string toString(const RNCVideoSrcCmcdStruct &value) {
  return "[Object RNCVideoSrcCmcdStruct]";
}

struct RNCVideoSrcTextTracksStruct {
  std::string title{};
  std::string language{};
  std::string type{};
  std::string uri{};
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, RNCVideoSrcTextTracksStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_title = map.find("title");
  if (tmp_title != map.end()) {
    fromRawValue(context, tmp_title->second, result.title);
  }
  auto tmp_language = map.find("language");
  if (tmp_language != map.end()) {
    fromRawValue(context, tmp_language->second, result.language);
  }
  auto tmp_type = map.find("type");
  if (tmp_type != map.end()) {
    fromRawValue(context, tmp_type->second, result.type);
  }
  auto tmp_uri = map.find("uri");
  if (tmp_uri != map.end()) {
    fromRawValue(context, tmp_uri->second, result.uri);
  }
}

static inline std::string toString(const RNCVideoSrcTextTracksStruct &value) {
  return "[Object RNCVideoSrcTextTracksStruct]";
}

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, std::vector<RNCVideoSrcTextTracksStruct> &result) {
  auto items = (std::vector<RawValue>)value;
  for (const auto &item : items) {
    RNCVideoSrcTextTracksStruct newItem;
    fromRawValue(context, item, newItem);
    result.emplace_back(newItem);
  }
}


struct RNCVideoSrcAdStruct {
  std::string adTagUrl{};
  std::string adLanguage{};
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, RNCVideoSrcAdStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_adTagUrl = map.find("adTagUrl");
  if (tmp_adTagUrl != map.end()) {
    fromRawValue(context, tmp_adTagUrl->second, result.adTagUrl);
  }
  auto tmp_adLanguage = map.find("adLanguage");
  if (tmp_adLanguage != map.end()) {
    fromRawValue(context, tmp_adLanguage->second, result.adLanguage);
  }
}

static inline std::string toString(const RNCVideoSrcAdStruct &value) {
  return "[Object RNCVideoSrcAdStruct]";
}

struct RNCVideoSrcBufferConfigLiveStruct {
  Float maxPlaybackSpeed{0.0};
  Float minPlaybackSpeed{0.0};
  int maxOffsetMs{0};
  int minOffsetMs{0};
  int targetOffsetMs{0};
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, RNCVideoSrcBufferConfigLiveStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_maxPlaybackSpeed = map.find("maxPlaybackSpeed");
  if (tmp_maxPlaybackSpeed != map.end()) {
    fromRawValue(context, tmp_maxPlaybackSpeed->second, result.maxPlaybackSpeed);
  }
  auto tmp_minPlaybackSpeed = map.find("minPlaybackSpeed");
  if (tmp_minPlaybackSpeed != map.end()) {
    fromRawValue(context, tmp_minPlaybackSpeed->second, result.minPlaybackSpeed);
  }
  auto tmp_maxOffsetMs = map.find("maxOffsetMs");
  if (tmp_maxOffsetMs != map.end()) {
    fromRawValue(context, tmp_maxOffsetMs->second, result.maxOffsetMs);
  }
  auto tmp_minOffsetMs = map.find("minOffsetMs");
  if (tmp_minOffsetMs != map.end()) {
    fromRawValue(context, tmp_minOffsetMs->second, result.minOffsetMs);
  }
  auto tmp_targetOffsetMs = map.find("targetOffsetMs");
  if (tmp_targetOffsetMs != map.end()) {
    fromRawValue(context, tmp_targetOffsetMs->second, result.targetOffsetMs);
  }
}

static inline std::string toString(const RNCVideoSrcBufferConfigLiveStruct &value) {
  return "[Object RNCVideoSrcBufferConfigLiveStruct]";
}

struct RNCVideoSrcBufferConfigStruct {
  Float minBufferMs{0.0};
  Float maxBufferMs{0.0};
  Float bufferForPlaybackMs{0.0};
  Float bufferForPlaybackAfterRebufferMs{0.0};
  Float maxHeapAllocationPercent{0.0};
  Float backBufferDurationMs{0.0};
  Float minBackBufferMemoryReservePercent{0.0};
  Float minBufferMemoryReservePercent{0.0};
  Float cacheSizeMB{0.0};
  RNCVideoSrcBufferConfigLiveStruct live{};
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, RNCVideoSrcBufferConfigStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_minBufferMs = map.find("minBufferMs");
  if (tmp_minBufferMs != map.end()) {
    fromRawValue(context, tmp_minBufferMs->second, result.minBufferMs);
  }
  auto tmp_maxBufferMs = map.find("maxBufferMs");
  if (tmp_maxBufferMs != map.end()) {
    fromRawValue(context, tmp_maxBufferMs->second, result.maxBufferMs);
  }
  auto tmp_bufferForPlaybackMs = map.find("bufferForPlaybackMs");
  if (tmp_bufferForPlaybackMs != map.end()) {
    fromRawValue(context, tmp_bufferForPlaybackMs->second, result.bufferForPlaybackMs);
  }
  auto tmp_bufferForPlaybackAfterRebufferMs = map.find("bufferForPlaybackAfterRebufferMs");
  if (tmp_bufferForPlaybackAfterRebufferMs != map.end()) {
    fromRawValue(context, tmp_bufferForPlaybackAfterRebufferMs->second, result.bufferForPlaybackAfterRebufferMs);
  }
  auto tmp_maxHeapAllocationPercent = map.find("maxHeapAllocationPercent");
  if (tmp_maxHeapAllocationPercent != map.end()) {
    fromRawValue(context, tmp_maxHeapAllocationPercent->second, result.maxHeapAllocationPercent);
  }
  auto tmp_backBufferDurationMs = map.find("backBufferDurationMs");
  if (tmp_backBufferDurationMs != map.end()) {
    fromRawValue(context, tmp_backBufferDurationMs->second, result.backBufferDurationMs);
  }
  auto tmp_minBackBufferMemoryReservePercent = map.find("minBackBufferMemoryReservePercent");
  if (tmp_minBackBufferMemoryReservePercent != map.end()) {
    fromRawValue(context, tmp_minBackBufferMemoryReservePercent->second, result.minBackBufferMemoryReservePercent);
  }
  auto tmp_minBufferMemoryReservePercent = map.find("minBufferMemoryReservePercent");
  if (tmp_minBufferMemoryReservePercent != map.end()) {
    fromRawValue(context, tmp_minBufferMemoryReservePercent->second, result.minBufferMemoryReservePercent);
  }
  auto tmp_cacheSizeMB = map.find("cacheSizeMB");
  if (tmp_cacheSizeMB != map.end()) {
    fromRawValue(context, tmp_cacheSizeMB->second, result.cacheSizeMB);
  }
  auto tmp_live = map.find("live");
  if (tmp_live != map.end()) {
    fromRawValue(context, tmp_live->second, result.live);
  }
}

static inline std::string toString(const RNCVideoSrcBufferConfigStruct &value) {
  return "[Object RNCVideoSrcBufferConfigStruct]";
}

struct RNCVideoSrcStruct {
  std::string uri{};
  bool isNetwork{false};
  bool isAsset{false};
  bool isLocalAssetFile{false};
  bool shouldCache{false};
  std::string type{};
  int mainVer{0};
  int patchVer{0};
  std::vector<RNCVideoSrcRequestHeadersStruct> requestHeaders{};
  Float startPosition{0.0};
  Float cropStart{0.0};
  Float cropEnd{0.0};
  int contentStartTime{0};
  RNCVideoSrcMetadataStruct metadata{};
  RNCVideoSrcDrmStruct drm{};
  RNCVideoSrcCmcdStruct cmcd{};
  bool textTracksAllowChunklessPreparation{false};
  std::vector<RNCVideoSrcTextTracksStruct> textTracks{};
  RNCVideoSrcAdStruct ad{};
  int minLoadRetryCount{0};
  RNCVideoSrcBufferConfigStruct bufferConfig{};
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, RNCVideoSrcStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_uri = map.find("uri");
  if (tmp_uri != map.end()) {
    fromRawValue(context, tmp_uri->second, result.uri);
  }
  auto tmp_isNetwork = map.find("isNetwork");
  if (tmp_isNetwork != map.end()) {
    fromRawValue(context, tmp_isNetwork->second, result.isNetwork);
  }
  auto tmp_isAsset = map.find("isAsset");
  if (tmp_isAsset != map.end()) {
    fromRawValue(context, tmp_isAsset->second, result.isAsset);
  }
  auto tmp_isLocalAssetFile = map.find("isLocalAssetFile");
  if (tmp_isLocalAssetFile != map.end()) {
    fromRawValue(context, tmp_isLocalAssetFile->second, result.isLocalAssetFile);
  }
  auto tmp_shouldCache = map.find("shouldCache");
  if (tmp_shouldCache != map.end()) {
    fromRawValue(context, tmp_shouldCache->second, result.shouldCache);
  }
  auto tmp_type = map.find("type");
  if (tmp_type != map.end()) {
    fromRawValue(context, tmp_type->second, result.type);
  }
  auto tmp_mainVer = map.find("mainVer");
  if (tmp_mainVer != map.end()) {
    fromRawValue(context, tmp_mainVer->second, result.mainVer);
  }
  auto tmp_patchVer = map.find("patchVer");
  if (tmp_patchVer != map.end()) {
    fromRawValue(context, tmp_patchVer->second, result.patchVer);
  }
  auto tmp_requestHeaders = map.find("requestHeaders");
  if (tmp_requestHeaders != map.end()) {
    fromRawValue(context, tmp_requestHeaders->second, result.requestHeaders);
  }
  auto tmp_startPosition = map.find("startPosition");
  if (tmp_startPosition != map.end()) {
    fromRawValue(context, tmp_startPosition->second, result.startPosition);
  }
  auto tmp_cropStart = map.find("cropStart");
  if (tmp_cropStart != map.end()) {
    fromRawValue(context, tmp_cropStart->second, result.cropStart);
  }
  auto tmp_cropEnd = map.find("cropEnd");
  if (tmp_cropEnd != map.end()) {
    fromRawValue(context, tmp_cropEnd->second, result.cropEnd);
  }
  auto tmp_contentStartTime = map.find("contentStartTime");
  if (tmp_contentStartTime != map.end()) {
    fromRawValue(context, tmp_contentStartTime->second, result.contentStartTime);
  }
  auto tmp_metadata = map.find("metadata");
  if (tmp_metadata != map.end()) {
    fromRawValue(context, tmp_metadata->second, result.metadata);
  }
  auto tmp_drm = map.find("drm");
  if (tmp_drm != map.end()) {
    fromRawValue(context, tmp_drm->second, result.drm);
  }
  auto tmp_cmcd = map.find("cmcd");
  if (tmp_cmcd != map.end()) {
    fromRawValue(context, tmp_cmcd->second, result.cmcd);
  }
  auto tmp_textTracksAllowChunklessPreparation = map.find("textTracksAllowChunklessPreparation");
  if (tmp_textTracksAllowChunklessPreparation != map.end()) {
    fromRawValue(context, tmp_textTracksAllowChunklessPreparation->second, result.textTracksAllowChunklessPreparation);
  }
  auto tmp_textTracks = map.find("textTracks");
  if (tmp_textTracks != map.end()) {
    fromRawValue(context, tmp_textTracks->second, result.textTracks);
  }
  auto tmp_ad = map.find("ad");
  if (tmp_ad != map.end()) {
    fromRawValue(context, tmp_ad->second, result.ad);
  }
  auto tmp_minLoadRetryCount = map.find("minLoadRetryCount");
  if (tmp_minLoadRetryCount != map.end()) {
    fromRawValue(context, tmp_minLoadRetryCount->second, result.minLoadRetryCount);
  }
  auto tmp_bufferConfig = map.find("bufferConfig");
  if (tmp_bufferConfig != map.end()) {
    fromRawValue(context, tmp_bufferConfig->second, result.bufferConfig);
  }
}

static inline std::string toString(const RNCVideoSrcStruct &value) {
  return "[Object RNCVideoSrcStruct]";
}

struct RNCVideoSelectedTextTrackStruct {
  std::string type{"system"};
  std::string value{};
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, RNCVideoSelectedTextTrackStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_type = map.find("type");
  if (tmp_type != map.end()) {
    fromRawValue(context, tmp_type->second, result.type);
  }
  auto tmp_value = map.find("value");
  if (tmp_value != map.end()) {
    fromRawValue(context, tmp_value->second, result.value);
  }
}

static inline std::string toString(const RNCVideoSelectedTextTrackStruct &value) {
  return "[Object RNCVideoSelectedTextTrackStruct]";
}

struct RNCVideoSelectedAudioTrackStruct {
  std::string type{"system"};
  std::string value{};
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, RNCVideoSelectedAudioTrackStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_type = map.find("type");
  if (tmp_type != map.end()) {
    fromRawValue(context, tmp_type->second, result.type);
  }
  auto tmp_value = map.find("value");
  if (tmp_value != map.end()) {
    fromRawValue(context, tmp_value->second, result.value);
  }
}

static inline std::string toString(const RNCVideoSelectedAudioTrackStruct &value) {
  return "[Object RNCVideoSelectedAudioTrackStruct]";
}

struct RNCVideoSelectedVideoTrackStruct {
  std::string type{"auto"};
  std::string value{};
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, RNCVideoSelectedVideoTrackStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_type = map.find("type");
  if (tmp_type != map.end()) {
    fromRawValue(context, tmp_type->second, result.type);
  }
  auto tmp_value = map.find("value");
  if (tmp_value != map.end()) {
    fromRawValue(context, tmp_value->second, result.value);
  }
}

static inline std::string toString(const RNCVideoSelectedVideoTrackStruct &value) {
  return "[Object RNCVideoSelectedVideoTrackStruct]";
}

struct RNCVideoDebugStruct {
  bool enable{false};
  bool thread{false};
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, RNCVideoDebugStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_enable = map.find("enable");
  if (tmp_enable != map.end()) {
    fromRawValue(context, tmp_enable->second, result.enable);
  }
  auto tmp_thread = map.find("thread");
  if (tmp_thread != map.end()) {
    fromRawValue(context, tmp_thread->second, result.thread);
  }
}

static inline std::string toString(const RNCVideoDebugStruct &value) {
  return "[Object RNCVideoDebugStruct]";
}

struct RNCVideoSubtitleStyleStruct {
  Float fontSize{0.0};
  Float paddingTop{0.0};
  Float paddingBottom{0.0};
  Float paddingLeft{0.0};
  Float paddingRight{0.0};
  Float opacity{1.0};
  bool subtitlesFollowVideo{true};
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, RNCVideoSubtitleStyleStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_fontSize = map.find("fontSize");
  if (tmp_fontSize != map.end()) {
    fromRawValue(context, tmp_fontSize->second, result.fontSize);
  }
  auto tmp_paddingTop = map.find("paddingTop");
  if (tmp_paddingTop != map.end()) {
    fromRawValue(context, tmp_paddingTop->second, result.paddingTop);
  }
  auto tmp_paddingBottom = map.find("paddingBottom");
  if (tmp_paddingBottom != map.end()) {
    fromRawValue(context, tmp_paddingBottom->second, result.paddingBottom);
  }
  auto tmp_paddingLeft = map.find("paddingLeft");
  if (tmp_paddingLeft != map.end()) {
    fromRawValue(context, tmp_paddingLeft->second, result.paddingLeft);
  }
  auto tmp_paddingRight = map.find("paddingRight");
  if (tmp_paddingRight != map.end()) {
    fromRawValue(context, tmp_paddingRight->second, result.paddingRight);
  }
  auto tmp_opacity = map.find("opacity");
  if (tmp_opacity != map.end()) {
    fromRawValue(context, tmp_opacity->second, result.opacity);
  }
  auto tmp_subtitlesFollowVideo = map.find("subtitlesFollowVideo");
  if (tmp_subtitlesFollowVideo != map.end()) {
    fromRawValue(context, tmp_subtitlesFollowVideo->second, result.subtitlesFollowVideo);
  }
}

static inline std::string toString(const RNCVideoSubtitleStyleStruct &value) {
  return "[Object RNCVideoSubtitleStyleStruct]";
}

struct RNCVideoControlsStylesStruct {
  bool hidePosition{false};
  bool hidePlayPause{false};
  bool hideForward{false};
  bool hideRewind{false};
  bool hideNext{false};
  bool hidePrevious{false};
  bool hideFullscreen{false};
  bool hideSeekBar{false};
  bool hideDuration{false};
  bool hideNavigationBarOnFullScreenMode{true};
  bool hideNotificationBarOnFullScreenMode{true};
  bool hideSettingButton{true};
  int seekIncrementMS{0};
  std::string liveLabel{};
};

static inline void fromRawValue(const PropsParserContext& context, const RawValue &value, RNCVideoControlsStylesStruct &result) {
  auto map = (butter::map<std::string, RawValue>)value;

  auto tmp_hidePosition = map.find("hidePosition");
  if (tmp_hidePosition != map.end()) {
    fromRawValue(context, tmp_hidePosition->second, result.hidePosition);
  }
  auto tmp_hidePlayPause = map.find("hidePlayPause");
  if (tmp_hidePlayPause != map.end()) {
    fromRawValue(context, tmp_hidePlayPause->second, result.hidePlayPause);
  }
  auto tmp_hideForward = map.find("hideForward");
  if (tmp_hideForward != map.end()) {
    fromRawValue(context, tmp_hideForward->second, result.hideForward);
  }
  auto tmp_hideRewind = map.find("hideRewind");
  if (tmp_hideRewind != map.end()) {
    fromRawValue(context, tmp_hideRewind->second, result.hideRewind);
  }
  auto tmp_hideNext = map.find("hideNext");
  if (tmp_hideNext != map.end()) {
    fromRawValue(context, tmp_hideNext->second, result.hideNext);
  }
  auto tmp_hidePrevious = map.find("hidePrevious");
  if (tmp_hidePrevious != map.end()) {
    fromRawValue(context, tmp_hidePrevious->second, result.hidePrevious);
  }
  auto tmp_hideFullscreen = map.find("hideFullscreen");
  if (tmp_hideFullscreen != map.end()) {
    fromRawValue(context, tmp_hideFullscreen->second, result.hideFullscreen);
  }
  auto tmp_hideSeekBar = map.find("hideSeekBar");
  if (tmp_hideSeekBar != map.end()) {
    fromRawValue(context, tmp_hideSeekBar->second, result.hideSeekBar);
  }
  auto tmp_hideDuration = map.find("hideDuration");
  if (tmp_hideDuration != map.end()) {
    fromRawValue(context, tmp_hideDuration->second, result.hideDuration);
  }
  auto tmp_hideNavigationBarOnFullScreenMode = map.find("hideNavigationBarOnFullScreenMode");
  if (tmp_hideNavigationBarOnFullScreenMode != map.end()) {
    fromRawValue(context, tmp_hideNavigationBarOnFullScreenMode->second, result.hideNavigationBarOnFullScreenMode);
  }
  auto tmp_hideNotificationBarOnFullScreenMode = map.find("hideNotificationBarOnFullScreenMode");
  if (tmp_hideNotificationBarOnFullScreenMode != map.end()) {
    fromRawValue(context, tmp_hideNotificationBarOnFullScreenMode->second, result.hideNotificationBarOnFullScreenMode);
  }
  auto tmp_hideSettingButton = map.find("hideSettingButton");
  if (tmp_hideSettingButton != map.end()) {
    fromRawValue(context, tmp_hideSettingButton->second, result.hideSettingButton);
  }
  auto tmp_seekIncrementMS = map.find("seekIncrementMS");
  if (tmp_seekIncrementMS != map.end()) {
    fromRawValue(context, tmp_seekIncrementMS->second, result.seekIncrementMS);
  }
  auto tmp_liveLabel = map.find("liveLabel");
  if (tmp_liveLabel != map.end()) {
    fromRawValue(context, tmp_liveLabel->second, result.liveLabel);
  }
}

static inline std::string toString(const RNCVideoControlsStylesStruct &value) {
  return "[Object RNCVideoControlsStylesStruct]";
}
class RNCVideoProps final : public ViewProps {
 public:
  RNCVideoProps() = default;
  RNCVideoProps(const PropsParserContext& context, const RNCVideoProps &sourceProps, const RawProps &rawProps);

#pragma mark - Props

  RNCVideoSrcStruct src{};
  bool allowsExternalPlayback{false};
  bool disableFocus{false};
  Float maxBitRate{0.0};
  std::string resizeMode{"none"};
  bool repeat{false};
  bool automaticallyWaitsToMinimizeStalling{false};
  int shutterColor{0};
  std::string audioOutput{"speaker"};
  RNCVideoSelectedTextTrackStruct selectedTextTrack{};
  RNCVideoSelectedAudioTrackStruct selectedAudioTrack{};
  RNCVideoSelectedVideoTrackStruct selectedVideoTrack{};
  bool paused{false};
  bool muted{false};
  bool controls{false};
  std::string filter{""};
  bool filterEnabled{false};
  Float volume{0.0};
  bool playInBackground{false};
  bool preventsDisplaySleepDuringVideoPlayback{false};
  Float preferredForwardBufferDuration{0.0};
  bool playWhenInactive{false};
  bool enterPictureInPictureOnLeave{false};
  std::string ignoreSilentSwitch{"inherit"};
  std::string mixWithOthers{"inherit"};
  Float rate{0.0};
  bool fullscreen{false};
  bool fullscreenAutorotate{false};
  std::string fullscreenOrientation{"all"};
  Float progressUpdateInterval{0.0};
  bool restoreUserInterfaceForPIPStopCompletionHandler{false};
  RNCVideoDebugStruct debug{};
  bool showNotificationControls{false};
  double currentPlaybackTime{0.0};
  bool disableDisconnectError{false};
  bool focusable{false};
  bool hideShutterView{false};
  bool reportBandwidth{false};
  RNCVideoSubtitleStyleStruct subtitleStyle{};
  int viewType{0};
  std::string bufferingStrategy{"Default"};
  RNCVideoControlsStylesStruct controlsStyles{};
  bool disableAudioSessionManagement{false};
};

} // namespace facebook::react
